# Generated by Django 5.1.6 on 2025-04-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('descriptions', models.TextField(null=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
